Repository Devscord-Team/Watchman, pull requests merged in 2022-04, with the labels that each got.

#213 AddRoles Tests
  Watchman.Discord.UnitTests/Users/UsersControllerTests.cs
Labels: Tests

#214 remove role
  Watchman.Discord.UnitTests/Users/UsersControllerTests.cs
Labels: Tests

#215 PrintRoles Tests
  Watchman.Discord.UnitTests/Users/UsersControllerTests.cs
Labels: Tests

#216 GetTrustedRoles Tests
  Watchman.Discord.UnitTests/Administration/AdministrationControllerTests.cs
Labels: Tests

#221 F/219 help descriptions
  Devscord.DiscordFramework/Commands/Responses/ResponsesCachingService.cs
  Watchman.Discord.IntegrationTests/Responses/ResponsesManagersTests.cs
  Watchman.Discord/Areas/Help/Services/HelpDBGeneratorService.cs
  Watchman.Discord/Areas/Help/Services/HelpMessageGeneratorService.cs
  Watchman.Discord/Areas/Help/Services/HelpService.cs
  Watchman.Discord/Extensions/WatchmanBotExtensions.cs
  Watchman.Discord/ResponsesManagers/HelpInformationsResponsesManager.cs
  Watchman.DomainModel.UnitTests/Responses/ResourcesResponsesServiceTests.cs
  Watchman.DomainModel/Help/Commands/AddOrUpdateHelpInformationsCommand.cs
  Watchman.DomainModel/Help/Commands/Handlers/AddHelpInformationCommandHandler.cs
  Watchman.DomainModel/Help/Commands/Handlers/AddOrUpdateHelpInformationsCommandHandler.cs
  Watchman.DomainModel/Help/HelpInformation.cs
  Watchman.DomainModel/Help/Queries/GetHelpInformationsQuery.cs
  Watchman.DomainModel/Help/Queries/GetHelpInformationsQueryResult.cs
  Watchman.DomainModel/Help/Queries/Handlers/GetHelpInformationsQueryHandler.cs
  Watchman.DomainModel/Responses/Resources/HelpDefaultResponses.json
  Watchman.DomainModel/Responses/Resources/HelpInformationsDefaultResponses.json
  Watchman.DomainModel/Responses/ResponsesGetterService.cs
  Watchman.DomainModel/Watchman.DomainModel.csproj
  Watchman.Web/Areas/Helps/Controllers/HelpsController.cs
Labels: enhancement

#222 release
  Devscord.DiscordFramework/Commands/Responses/ResponsesCachingService.cs
  Watchman.Discord.IntegrationTests/Responses/ResponsesManagersTests.cs
  Watchman.Discord/Areas/Help/Services/HelpDBGeneratorService.cs
  Watchman.Discord/Areas/Help/Services/HelpMessageGeneratorService.cs
  Watchman.Discord/Areas/Help/Services/HelpService.cs
  Watchman.Discord/Extensions/WatchmanBotExtensions.cs
  Watchman.Discord/ResponsesManagers/HelpInformationsResponsesManager.cs
  Watchman.DomainModel.UnitTests/Responses/ResourcesResponsesServiceTests.cs
  Watchman.DomainModel/Help/Commands/AddOrUpdateHelpInformationsCommand.cs
  Watchman.DomainModel/Help/Commands/Handlers/AddHelpInformationCommandHandler.cs
  Watchman.DomainModel/Help/Commands/Handlers/AddOrUpdateHelpInformationsCommandHandler.cs
  Watchman.DomainModel/Help/HelpInformation.cs
  Watchman.DomainModel/Help/Queries/GetHelpInformationsQuery.cs
  Watchman.DomainModel/Help/Queries/GetHelpInformationsQueryResult.cs
  Watchman.DomainModel/Help/Queries/Handlers/GetHelpInformationsQueryHandler.cs
  Watchman.DomainModel/Responses/Resources/HelpDefaultResponses.json
  Watchman.DomainModel/Responses/Resources/HelpInformationsDefaultResponses.json
  Watchman.DomainModel/Responses/ResponsesGetterService.cs
  Watchman.DomainModel/Watchman.DomainModel.csproj
  Watchman.Web/Areas/Helps/Controllers/HelpsController.cs
Labels: release-merge

#223 release
  Watchman.DomainModel/Responses/Resources/HelpDefaultResponses.json
  Watchman.DomainModel/Responses/Resources/UsersDefaultResponses.json
Labels: release-merge

#224 Json for one command
  Watchman.Discord/Areas/Help/Controllers/HelpController.cs
  Watchman.Discord/Areas/Help/Services/HelpMessageGeneratorService.cs
  Watchman.Discord/Areas/Help/Services/HelpService.cs
Labels: bug

#230 F/225 create web client
  Watchman.WebClient/App.razor
  Watchman.WebClient/Areas/Auth/AccountsController.cs
  Watchman.WebClient/Areas/Auth/Discord/DiscordAuthenticationOptionsExtensions.cs
  Watchman.WebClient/Areas/Auth/Discord/DiscordDefaults.cs
  Watchman.WebClient/Areas/Auth/Discord/DiscordHandler.cs
  Watchman.WebClient/Areas/Auth/Discord/DiscordOptions.cs
  Watchman.WebClient/Areas/Auth/UsersService.cs
  Watchman.WebClient/Data/WeatherForecast.cs
  Watchman.WebClient/Data/WeatherForecastService.cs
  Watchman.WebClient/Pages/Counter.razor
  Watchman.WebClient/Pages/Error.cshtml
  Watchman.WebClient/Pages/Error.cshtml.cs
  Watchman.WebClient/Pages/FetchData.razor
  Watchman.WebClient/Pages/Guild.razor
  Watchman.WebClient/Pages/Index.razor
  Watchman.WebClient/Pages/RedirectToLogin.razor
  Watchman.WebClient/Pages/User.razor
  Watchman.WebClient/Pages/_Host.cshtml
  Watchman.WebClient/Pages/_Layout.cshtml
  Watchman.WebClient/Program.cs
  Watchman.WebClient/Shared/MainLayout.razor
  Watchman.WebClient/Shared/MainLayout.razor.css
  Watchman.WebClient/Shared/NavMenu.razor
  Watchman.WebClient/Shared/NavMenu.razor.css
  Watchman.WebClient/Shared/SurveyPrompt.razor
  Watchman.WebClient/Watchman.WebClient.csproj
  Watchman.WebClient/_Imports.razor
  Watchman.WebClient/wwwroot/css/bootstrap/bootstrap.min.css
  Watchman.WebClient/wwwroot/css/bootstrap/bootstrap.min.css.map
  Watchman.WebClient/wwwroot/css/open-iconic/FONT-LICENSE
  Watchman.WebClient/wwwroot/css/open-iconic/ICON-LICENSE
  Watchman.WebClient/wwwroot/css/open-iconic/README.md
  Watchman.WebClient/wwwroot/css/open-iconic/font/css/open-iconic-bootstrap.min.css
  Watchman.WebClient/wwwroot/css/open-iconic/font/fonts/open-iconic.eot
  Watchman.WebClient/wwwroot/css/open-iconic/font/fonts/open-iconic.otf
  Watchman.WebClient/wwwroot/css/open-iconic/font/fonts/open-iconic.svg
  Watchman.WebClient/wwwroot/css/open-iconic/font/fonts/open-iconic.ttf
  Watchman.WebClient/wwwroot/css/open-iconic/font/fonts/open-iconic.woff
  Watchman.WebClient/wwwroot/css/site.css
  Watchman.WebClient/wwwroot/favicon.ico
  Watchman.sln
Labels: enhancement

#232 release
  Watchman.Common/Models/TimeRange.cs
  Watchman.Discord/Areas/Muting/Controllers/MuteUserController.cs
Labels: release-merge
